image: pongch/truffle:ci  
 
before_script:
 - cd loo-contract
 - npm install
stages:
 - build
 - test
 
build:
 stage: build
 script:
  - testrpc -p 8545 & 
  - truffle compile
  - truffle migrate --network development
 
test:
 stage: test
 script:     
   - npm run coverage
 
