image: pongch/truffle:ci  
 
before_script:
 - cd LAST-contract
 - npm install
stages:
 - build_contract
 - test_contract
 
build_contract:
 stage: build_contract
 script:
  - truffle compile
  - ganache-cli -p 8545 & truffle migrate --network development
 
test_contract:
 stage: test_contract
 script:     
   - npm run coverage
 
