stages:
 - build_contract
 - test_contract
 - build_server
 
build_contract:
 image: pongch/truffle:ci  
 stage: build_contract
 script:
  - cd LAST-contract
  - npm install
  - truffle compile
  - ganache-cli -p 8545 & truffle migrate --network development
 
test_contract:
 image: pongch/truffle:ci  
 stage: test_contract
 script:    
   - cd LAST-contract
   - npm install 
   - npm run coverage

build_server:
  image: node:alpine
  stage: build_server
  script:
    - cd LAST-server
    - npm install
integration_build:
  image: tmaier/docker-compose:latest
  stage: integration_build

  services:
    - docker:dind

  before_script:
    - docker info
    - docker-compose --version

  build_image:
    stage: build
    script:
      - docker-compose build

