image: pongch/truffle:ci  
 
before_script:
 - cd loo-contract
 - npm install
stages:
 - build
 - test
 
build:
 stage: build
 script:
  - truffle compile
  - ganache-cli -p 8545 & truffle migrate --network development
 
test:
 stage: test
 script:     
   - ganache-cli -p 8545 & truffle test
 
