image: pongch/truffle:latest    
 
before_script:
 - npm install -g ethereumjs-testrpc
 - cd loo-contract
 
stages:
 - build
 - test
 
build:
 stage: build
 script:
   - truffle compile
 
test:
 stage: test
 script:
   - testrpc -p 8545 &     
   - truffle test
 
