version: "2"
services:
  last-server:
    container_name: last-server
    restart: always
    depends_on: 
      - last-db
    image: pongch/last-server:latest
    ports:
      - "3000:3000"
    links:
      - last-db
  last-db:
    container_name: last-db
    volumes:
      - ./data:/bitnami
    ports:
      - "27017:27017"
    image: aashreys/mongo-auth:latest
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=my_user
      - MONGODB_ADMIN_PASS=last_db4312
      - MONGODB_APPLICATION_DATABASE=last-db
      - MONGODB_APPLICATION_USER=my_user
      - MONGODB_APPLICATION_PASS=last_db4312
    ports:
      - "27017:27017"  