apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: last-server
  name: last-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: last-server
    spec:
      containers:
      - image: pongch/last-server:latest
        name: last-server
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
